DROP TABLE IF EXISTS Tracks;
CREATE TABLE [dbo].[Tracks]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[AlbumId] INT FOREIGN KEY REFERENCES Album(Id),
	[Disk] INT NULL,
	[TrackNumber] INT NOT NULL,
	[TrackTitle] VARCHAR(MAX) NOT NULL,
	[TrackArtist] VARCHAR(MAX) NULL,
	[Duration] VARCHAR(MAX) NOT NULL,
	[Path] VARCHAR(MAX) NOT NULL
)